### ISSUE TITLE
Cant pass arguments

### ISSUE THREAD

**Issue by S-P-E-C-T-R-3** [lyyka/facial-recognition-emoji#1] opened 2020-08-12 18:28 UTC
usage: on_image.py [-h] -m MODE -i IMAGE
on_image.py: error: the following arguments are required: -m/--mode, -i/--image

Process finished with exit code 2

**Comment by lyyka** [comment] 2020-08-12 20:36
Hi @Surya-047 , thank you for opening the issue.

The issue only happens when I try to run the file through automated function in IDE (like a configuration in PyCharm) because it automatically runs the script without passing any arguments (which are required here).

I was unable to reproduce the issue otherwise. Here is how to run both video and image scripts manually from the command line:
**Video**
`python on_video.py -m [emoji | blur | rect]`

**Image**
`python on_image.py -i images\faces.jpg -m [emoji | blur | rect]`

**Comment by S-P-E-C-T-R-3** [comment] 2020-08-13 05:35
![image](https://user-images.githubusercontent.com/69527330/90097922-b1e83d00-dd54-11ea-8edb-b77b142cb369.png)
When i try to run using terminal it shows this and camera does't opens up.

**Comment by lyyka** [comment] 2020-08-13 08:35
@Surya-047 You have to type "python" before the file name you want to run. Seems the problem still might be on your side.

Also, [blur | rect | emoji] is just a markup to show you can pick any of those options. In the command line arguments you can type only one of them..

**Comment by S-P-E-C-T-R-3** [comment] 2020-08-13 09:33
C:\Users\user\project\Emojify>python on_video.py -m [emoji | blur | rect]

'blur' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lyyka** [comment] 2020-08-13 10:46
That is not valid command to run this script. Please read all of the above comments.

Closing the issue as there isn't one.

**Closed as completed by lyyka** 2020-08-13 10:46 UTC
